dataArray[0] = Deviceid;
  dataArray[1] = Auto;
  dataArray[2] = SetVolt1;
  dataArray[3] = Min_Volt_Fan;
  dataArray[4] = Max_Volt_Fan;
  dataArray[5] = Min_Temp1;
  dataArray[6] = Max_Temp1;
  dataArray[7] = Min_Temp2;
  dataArray[8] = Max_Temp2;
  dataArray[9] = Min_Volt_Damper;
  dataArray[10] = Max_Volt_Damper;
  dataArray[11] = Min_CO2;
  dataArray[12] = Max_CO2;
  dataArray[13] = CO2;                          // co2 value  34
  dataArray[14] = DP;                           // dp_ value  35
  dataArray[15] = int(massConcentrationPm2p5);  // pm2.5 value
  dataArray[16] = int(massConcentrationPm10p0);  // pm2.5 value
  dataArray[17] = int(vocIndex);                // tvoc index
  dataArray[18] = int(ambientHumidity);         // humidity
  dataArray[19] = int(ambientTemperature);      // temp1 pm
  dataArray[20] = average_Temp;                 // temp2     36
  dataArray[21] = //FAN_RPM;                      // fan_rpm   15
  dataArray[22] = Fan_ACVoltage;                // volt
  dataArray[23] = average_ACC;                  // current   39
  dataArray[24] = SetVolt2;
  dataArray[25] = controlBy;